name: Deploy Docker to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH, Create ENV and Deploy
        uses: appleboy/ssh-action@v1.0.3
        # BƯỚC KHẮC PHỤC: Lấy Secret của Github gán vào một biến môi trường của môi trường ảo này
        env:
          SECRET_ENV_FILE: ${{ secrets.ENV_FILE }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          # Truyền biến môi trường ảo đó vào bên trong phiên SSH
          envs: SECRET_ENV_FILE
          script: |
            cd ~/my-first-cicd
            
            git reset --hard
            git pull origin main
            
            # Ghi nội dung biến vào file .env trên máy chủ EC2
            echo "$SECRET_ENV_FILE" > .env
            
            # Khởi động Docker
            docker-compose down
            docker-compose up -d --build
            
            # Dọn rác
            docker image prune -f
